### ISSUE TITLE
Generator stopped working after refactoring

### ISSUE THREAD

**Issue by kofanov** [rrmanzano/maui-bindableproperty-generator#7]
Hello! Thanks again for great tool!

After a little refactoring, the generator stopped working. Unfortunately, the error description does not allow me to understand exactly where the problem occurs. The project is very large and it is not possible to check all the files. Is it possible to output more information about the problem that is occurring?

Unfortunately, I can't compile the project anymore :(

----------------------------------

Warning	CS8785	Generator 'AutoBindablePropertyGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentNullException' with message 'Value cannot be null.
Parameter name: text'	[MY PROJECT NAME] (net7.0-ios)	C:\......[PATH TO MY PROJECT]....csproj	1	Active	Generator threw the following exception:
'System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at Microsoft.CodeAnalysis.Text.SourceText.From(String text, Encoding encoding, SourceHashAlgorithm checksumAlgorithm)
   at Maui.BindableProperty.Generator.Core.BindableProperty.AutoBindablePropertyGenerator.<>c__DisplayClass3_0.<Execute>b__0(INamedTypeSymbol attributeSymbol, IGrouping`2 group)
   at Maui.BindableProperty.Generator.Helpers.ExecutionContextExtensions.EachField[T](GeneratorExecutionContext context, String metadataName, Action`2 action)
   at Maui.BindableProperty.Generator.Core.BindableProperty.AutoBindablePropertyGenerator.Execute(GeneratorExecutionContext context)
   at Microsoft.CodeAnalysis.SourceGeneratorAdaptor.<Initialize>b__5_5(SourceProductionContext productionContext, GeneratorContextBuilder contextBuilder)
   at Microsoft.CodeAnalysis.UserFunctionExtensions.<>c__DisplayClass3_0`2.<WrapUserAction>b__0(TInput1 input1, TInput2 input2, CancellationToken token)'.

**Comment by rrmanzano** [comment]
Hi @kofanov, unfortunately, I can't replicate the issue, I created a new solution using NET 7 with these fields, and all looks good

![5uMdhnecsf](https://user-images.githubusercontent.com/19593017/206338367-1d2255c6-2617-46a4-b4db-69120c41f23e.png)

Have you already tried deleting the "bin" and "obj" folders and reopening the solution?

**Comment by kofanov** [comment]
Hello. Thank you for your feedback! I eventually found out what the problem was: I made a nested partial class. I just worked hard and didn't pay attention to it.

Is it possible to somehow make a more detailed description of the error in the generator? For example, include the name of the class in it to understand where to look. In my case, after refactoring a lot of classes, the project simply stopped compiling and it was completely unclear where to look for the problem. But the worst thing is that the generator stopped generating files altogether, which is why it was not possible to study the generated code.

As a result, I downloaded the source code of another similar generator (with a simpler code structure to make it easier to understand), embedded it into the project, looked at the generated code and only then saw that the problem was in the partial class.

Thanks again!

**Comment by rrmanzano** [comment]
Hi @kofanov I just sent a new version that includes a new wey to handle the errors, this change will provide detail about the generator. Thanks again for your feedback.

Here is the new version
https://github.com/rrmanzano/maui-bindableproperty-generator/releases/tag/0.10.0
